<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#数组的合并" data-toc-modified-id="数组的合并-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>数组的合并</a></span><ul class="toc-item"><li><span><a href="#np.vstack-沿纵轴拼接" data-toc-modified-id="np.vstack-沿纵轴拼接-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>np.vstack 沿纵轴拼接</a></span></li><li><span><a href="#np.hstack-沿横轴拼接" data-toc-modified-id="np.hstack-沿横轴拼接-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>np.hstack 沿横轴拼接</a></span></li><li><span><a href="#指定拼接方向的np.concatenate()" data-toc-modified-id="指定拼接方向的np.concatenate()-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>指定拼接方向的np.concatenate()</a></span></li></ul></li><li><span><a href="#数组的分割" data-toc-modified-id="数组的分割-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>数组的分割</a></span><ul class="toc-item"><li><span><a href="#np.hsplit-横向进行分割" data-toc-modified-id="np.hsplit-横向进行分割-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>np.hsplit 横向进行分割</a></span></li><li><span><a href="#np.vsplit()横向进行分割" data-toc-modified-id="np.vsplit()横向进行分割-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>np.vsplit()横向进行分割</a></span></li><li><span><a href="#可指定方向的np.array_split()" data-toc-modified-id="可指定方向的np.array_split()-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>可指定方向的np.array_split()</a></span></li></ul></li></ul></div>

In [1]:
 import numpy as np

In [2]:
#全部行都能输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# 数组的合并

In [3]:
a = np.array([[1, 2,3], [7, 8, 9]])
b = np.array([[100, 101, 102], [103, 104, 105]])
c = np.array([[0,0], [0, 0]])

In [4]:
a
b
c

array([[1, 2, 3],
       [7, 8, 9]])

array([[100, 101, 102],
       [103, 104, 105]])

array([[0, 0],
       [0, 0]])

## np.vstack 沿纵轴拼接

**在纵向拼接， 增加的是行，列不变**

In [5]:
np.vstack((a,b))

array([[  1,   2,   3],
       [  7,   8,   9],
       [100, 101, 102],
       [103, 104, 105]])

In [6]:
np.vstack((a,c))   #维度必须匹配

ValueError: all the input array dimensions except for the concatenation axis must match exactly

## np.hstack 沿横轴拼接

**在横向拼接， 增加的是列，行不变**

In [7]:
a = np.array([[1, 2,3], [7, 8, 9]])
b = np.array([[100, 101, 102], [103, 104, 105]])
c = np.array([[0,0], [0, 0]])

In [8]:
a
b
c

array([[1, 2, 3],
       [7, 8, 9]])

array([[100, 101, 102],
       [103, 104, 105]])

array([[0, 0],
       [0, 0]])

In [9]:
np.hstack((a,b))

array([[  1,   2,   3, 100, 101, 102],
       [  7,   8,   9, 103, 104, 105]])

In [10]:
np.hstack((a,c))

array([[1, 2, 3, 0, 0],
       [7, 8, 9, 0, 0]])

## 指定拼接方向的np.concatenate()

**参数axis=0默认在纵轴上拼接，axis=1横向拼接**

In [11]:
a = np.array([[1, 2,3], [7, 8, 9]])
b = np.array([[100, 101, 102], [103, 104, 105]])
c = np.array([[0,0], [0, 0]])

In [12]:
a
b
c

array([[1, 2, 3],
       [7, 8, 9]])

array([[100, 101, 102],
       [103, 104, 105]])

array([[0, 0],
       [0, 0]])

In [13]:
np.concatenate((a,b), axis=0)   #axis=0默认在纵轴上拼接

array([[  1,   2,   3],
       [  7,   8,   9],
       [100, 101, 102],
       [103, 104, 105]])

In [14]:
np.concatenate((a,b), axis=1)   #axis=1在横轴上拼接

array([[  1,   2,   3, 100, 101, 102],
       [  7,   8,   9, 103, 104, 105]])

# 数组的分割

In [15]:
a = np.arange(1,37).reshape(4,9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

## np.hsplit 横向进行分割

In [16]:
b = np.hsplit(a,3)    # 第二个参数只写一个整数时，会在横向进行平均分割
b

[array([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21],
        [28, 29, 30]]), array([[ 4,  5,  6],
        [13, 14, 15],
        [22, 23, 24],
        [31, 32, 33]]), array([[ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27],
        [34, 35, 36]])]

In [17]:
for i in b:
    print(i)
    print('*'*30)

[[ 1  2  3]
 [10 11 12]
 [19 20 21]
 [28 29 30]]
******************************
[[ 4  5  6]
 [13 14 15]
 [22 23 24]
 [31 32 33]]
******************************
[[ 7  8  9]
 [16 17 18]
 [25 26 27]
 [34 35 36]]
******************************


In [18]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [19]:
np.hsplit(a,(3,5))   #在第三列和第五列的后面划一刀

[array([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21],
        [28, 29, 30]]), array([[ 4,  5],
        [13, 14],
        [22, 23],
        [31, 32]]), array([[ 6,  7,  8,  9],
        [15, 16, 17, 18],
        [24, 25, 26, 27],
        [33, 34, 35, 36]])]

In [20]:
np.hsplit(a,(3,5,6,7)) 

[array([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21],
        [28, 29, 30]]), array([[ 4,  5],
        [13, 14],
        [22, 23],
        [31, 32]]), array([[ 6],
        [15],
        [24],
        [33]]), array([[ 7],
        [16],
        [25],
        [34]]), array([[ 8,  9],
        [17, 18],
        [26, 27],
        [35, 36]])]

## np.vsplit()横向进行分割

In [21]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [22]:
np.vsplit(a,4)

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24, 25, 26, 27]]),
 array([[28, 29, 30, 31, 32, 33, 34, 35, 36]])]

In [23]:
np.vsplit(a,(1,3))

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27]]),
 array([[28, 29, 30, 31, 32, 33, 34, 35, 36]])]

## 可指定方向的np.array_split()

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [25]:
np.array_split(a,(1,3),axis=0)

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27]]),
 array([[28, 29, 30, 31, 32, 33, 34, 35, 36]])]

In [26]:
np.array_split(a,(1,3),axis=1)

[array([[ 1],
        [10],
        [19],
        [28]]), array([[ 2,  3],
        [11, 12],
        [20, 21],
        [29, 30]]), array([[ 4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18],
        [22, 23, 24, 25, 26, 27],
        [31, 32, 33, 34, 35, 36]])]