<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#ndarray对象的属性" data-toc-modified-id="ndarray对象的属性-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>ndarray对象的属性</a></span><ul class="toc-item"><li><span><a href="#数组的形状ndarray.shape" data-toc-modified-id="数组的形状ndarray.shape-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>数组的形状ndarray.shape</a></span></li><li><span><a href="#数组的维度ndarray.ndim" data-toc-modified-id="数组的维度ndarray.ndim-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>数组的维度ndarray.ndim</a></span></li><li><span><a href="#查看数组中的元素个数ndarray.size" data-toc-modified-id="查看数组中的元素个数ndarray.size-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>查看数组中的元素个数ndarray.size</a></span></li><li><span><a href="#查看数组中的元素的数据类型ndarray.dtype" data-toc-modified-id="查看数组中的元素的数据类型ndarray.dtype-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>查看数组中的元素的数据类型ndarray.dtype</a></span></li><li><span><a href="#查看数组中每个元素所占的内存字节数ndarray.itemsize" data-toc-modified-id="查看数组中每个元素所占的内存字节数ndarray.itemsize-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>查看数组中每个元素所占的内存字节数ndarray.itemsize</a></span></li></ul></li><li><span><a href="#ndarray对象的方法一维度变换" data-toc-modified-id="ndarray对象的方法一维度变换-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>ndarray对象的方法一维度变换</a></span><ul class="toc-item"><li><span><a href="#改变数组的形状ndarray.reshape（不改变原数组）" data-toc-modified-id="改变数组的形状ndarray.reshape（不改变原数组）-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>改变数组的形状ndarray.reshape（不改变原数组）</a></span></li><li><span><a href="#改变数组的形状ndarray.resize(改变原数组)" data-toc-modified-id="改变数组的形状ndarray.resize(改变原数组)-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>改变数组的形状ndarray.resize(改变原数组)</a></span></li><li><span><a href="#返回一个一维数组" data-toc-modified-id="返回一个一维数组-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>返回一个一维数组</a></span><ul class="toc-item"><li><span><a href="#ndarray.flatten" data-toc-modified-id="ndarray.flatten-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>ndarray.flatten</a></span></li><li><span><a href="#np.ravel()" data-toc-modified-id="np.ravel()-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>np.ravel()</a></span></li><li><span><a href="#通过reshape改变形状" data-toc-modified-id="通过reshape改变形状-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>通过reshape改变形状</a></span></li></ul></li></ul></li><li><span><a href="#ndarray对象的方法—数组转列表ndarray.tolist" data-toc-modified-id="ndarray对象的方法—数组转列表ndarray.tolist-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>ndarray对象的方法—数组转列表ndarray.tolist</a></span></li><li><span><a href="#ndarray的索引与切片" data-toc-modified-id="ndarray的索引与切片-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>ndarray的索引与切片</a></span><ul class="toc-item"><li><span><a href="#一维ndarray的索引与切片" data-toc-modified-id="一维ndarray的索引与切片-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>一维ndarray的索引与切片</a></span></li><li><span><a href="#多维ndarray的索引与切片" data-toc-modified-id="多维ndarray的索引与切片-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>多维ndarray的索引与切片</a></span></li><li><span><a href="#布尔索引" data-toc-modified-id="布尔索引-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>布尔索引</a></span></li></ul></li></ul></div>

In [1]:
 import numpy as np

In [2]:
#全部行都能输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# ndarray对象的属性

In [3]:
#为了确保大家都能生成一样的数组, 我们先设置随机数种子
np.random.seed(123)
x1 = np.random.randint(1,10, size=6) # 一维数组
x2 = np.random.randint(1,10, size=(3, 4)) # 二维数组
x3 = np.random.randint(1,10, size=(3, 4, 5)) # 三维数组

In [4]:
x1
x2
x3

array([3, 3, 7, 2, 4, 7])

array([[2, 1, 2, 1],
       [1, 4, 5, 1],
       [1, 5, 2, 8]])

array([[[4, 3, 5, 8, 3],
        [5, 9, 1, 8, 4],
        [5, 7, 2, 6, 7],
        [3, 2, 9, 4, 6]],

       [[1, 3, 7, 3, 5],
        [5, 7, 4, 1, 7],
        [5, 8, 7, 8, 2],
        [6, 8, 3, 5, 9]],

       [[2, 3, 2, 2, 4],
        [6, 1, 9, 2, 7],
        [4, 4, 6, 8, 3],
        [4, 4, 4, 9, 7]]])

## 数组的形状ndarray.shape

In [5]:
#查看数据的形状
x1.shape
x2.shape
x3.shape

(6,)

(3, 4)

(3, 4, 5)

## 数组的维度ndarray.ndim

In [6]:
x1.ndim
x2.ndim
x3.ndim

1

2

3

## 查看数组中的元素个数ndarray.size

In [7]:
x1.size
x2.size
x3.size

6

12

60

## 查看数组中的元素的数据类型ndarray.dtype

In [8]:
x1.dtype
x2.dtype
x3.dtype

dtype('int32')

dtype('int32')

dtype('int32')

## 查看数组中每个元素所占的内存字节数ndarray.itemsize

In [9]:
x1.itemsize
x2.itemsize
x3.itemsize

4

4

4

In [10]:
# 数组的 dtype 为 int8（一个字节）
x = np.array([1,2,3,4,5], dtype = np.int8)
x.itemsize

1

In [11]:
x = np.array([1,2,3,4,5], dtype = np.float64)
x.itemsize

8

# ndarray对象的方法一维度变换

In [12]:
m = np.random.randint(1, 100,(2, 3, 4))
m

array([[[10, 88, 15, 84],
        [71, 13, 55, 28],
        [39, 18, 62, 75]],

       [[66, 48, 17,  6],
        [87, 47, 16, 60],
        [41, 26, 46, 50]]])

## 改变数组的形状ndarray.reshape（不改变原数组）

In [17]:
m.reshape(3,8)      #不改变原数组，会返回新的数组

array([[ 1, 36, 30,  2, 84, 69, 31,  8],
       [94, 61, 66, 77, 68, 45, 52,  8],
       [89, 71, 14, 29, 64, 85, 37, 97]])

In [18]:
m.shape

(2, 3, 4)

In [19]:
m.reshape(3,7)     #注意这点，要保证reshape前后数组中的元素是一样的

ValueError: cannot reshape array of size 24 into shape (3,7)

## 改变数组的形状ndarray.resize(改变原数组)

In [20]:
m = np.random.randint(1, 100,(2, 3, 4))
m

array([[[41, 89, 64, 59],
        [78,  9, 79,  7],
        [66, 95, 71, 41]],

       [[75, 77, 77, 26],
        [ 8, 14, 45,  2],
        [42, 79, 57, 88]]])

In [21]:
m.resize(4,6) #改变原数组

In [22]:
m 

array([[41, 89, 64, 59, 78,  9],
       [79,  7, 66, 95, 71, 41],
       [75, 77, 77, 26,  8, 14],
       [45,  2, 42, 79, 57, 88]])

In [23]:
m.shape

(4, 6)

In [27]:
m.shape

(2, 3, 4)

## 返回一个一维数组

### ndarray.flatten

In [39]:
m = np.random.randint(1, 100,(2, 3, 4))
m

array([[[ 6, 82, 36, 78],
        [26, 98, 94, 71],
        [59, 30, 82, 22]],

       [[17, 31, 56, 81],
        [31, 13, 91, 84],
        [17, 93, 39, 99]]])

In [40]:
n = m.flatten()  #不改变原数组
n 

array([ 6, 82, 36, 78, 26, 98, 94, 71, 59, 30, 82, 22, 17, 31, 56, 81, 31,
       13, 91, 84, 17, 93, 39, 99])

### np.ravel()

In [42]:
m

array([[[ 6, 82, 36, 78],
        [26, 98, 94, 71],
        [59, 30, 82, 22]],

       [[17, 31, 56, 81],
        [31, 13, 91, 84],
        [17, 93, 39, 99]]])

In [43]:
m.ravel()

array([ 6, 82, 36, 78, 26, 98, 94, 71, 59, 30, 82, 22, 17, 31, 56, 81, 31,
       13, 91, 84, 17, 93, 39, 99])

In [38]:
m

array([[[36, 59, 39,  2],
        [53, 18, 46, 23],
        [54, 90, 75,  1]],

       [[36, 84, 95, 72],
        [40, 88, 84, 79],
        [30, 20, 38,  2]]])

### 通过reshape改变形状

In [46]:
m.reshape(1,-1)

array([[ 6, 82, 36, 78, 26, 98, 94, 71, 59, 30, 82, 22, 17, 31, 56, 81,
        31, 13, 91, 84, 17, 93, 39, 99]])

In [47]:
m.reshape(-1,1)

array([[ 6],
       [82],
       [36],
       [78],
       [26],
       [98],
       [94],
       [71],
       [59],
       [30],
       [82],
       [22],
       [17],
       [31],
       [56],
       [81],
       [31],
       [13],
       [91],
       [84],
       [17],
       [93],
       [39],
       [99]])

这种改变的就是原数组的形状而已

# ndarray对象的方法—数组转列表ndarray.tolist

有时候我们需要把把数组转化为列表来处理数据，因为列表有很多方法

之前我们有学过ndarray.astype()用来修改数组元素的数据类型

也知道怎么把列表 元组变成数组，反过来我再学一个怎么把ndarray变成列表

In [58]:
a  = np.array([1, 2, 3, 4, 5, 6, 7, 8])   #列表变数组
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
b = a.tolist()  #不会改变原数组，重新返回一个新生成的列表
b

[1, 2, 3, 4, 5, 6, 7, 8]

In [53]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

# ndarray的索引与切片

**和字符串 列表 元祖基本上是一样的**  
[开始位置, 终止位置， 步长和方向]

## 一维ndarray的索引与切片

In [13]:
a = np.arange(5,16)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**索引单个元素**

In [14]:
a[1]

6

In [15]:
a[-1]

15

In [16]:
a[-2]

14

**多个元素的连续索引**

In [17]:
a[0:3]

array([5, 6, 7])

In [18]:
a[3:8]

array([ 8,  9, 10, 11, 12])

In [19]:
a[5:]

array([10, 11, 12, 13, 14, 15])

In [20]:
a[5:-1]

array([10, 11, 12, 13, 14])

**间隔索引**

In [21]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
a[0:6:2]

array([5, 7, 9])

In [23]:
a[0::4]

array([ 5,  9, 13])

In [24]:
a[::-2]

array([15, 13, 11,  9,  7,  5])

## 多维ndarray的索引与切片

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a[0]

array([1, 2, 3])

In [27]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a[0][1]

2

In [29]:
a[2][:]

array([7, 8, 9])

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a[0:2,0]   #[行,列]

array([1, 4])

In [32]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a[:,1]

array([2, 5, 8])

In [34]:
a[1]==a[1,:]

array([ True,  True,  True])

## 布尔索引 

当结果对象是布尔运算（例如比较运算符）的结果时，将使用此类型的高级索引。

In [35]:
x = np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
x>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11])

In [38]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [39]:
np.isnan(a)

array([ True, False, False,  True, False, False, False])

In [40]:
a[np.isnan(a)]

array([nan, nan])